<li class="item">
                <div class="item-img"> <a class="item-img-inner" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]"> <img class="j-lazy" src="[field:litpic/]" data-original="[field:litpic/]" width="480" height="300" alt="[field:title/]"> </a> </div>
                <div class="item-content">
                    <p class="item-title"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a></p>
                    <p class="item-date">[field:pubdate function='strftime("%Y年%m月%d日",@me)'/]</p>
                </div>
            </li>