<div class="swiper-slide">
          <div class="thslidelist gundongimg ">
           <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" class="silde_a_border"> <img class="th-img thslide2-img-height" src="{dede:global.cfg_cmspath/}/public/img/8c34361207c484784cae4db067847eae.jpg" alt="[field:title/]" title="[field:title/]" /> </a>
           <div class="thslidetitle">
            <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]</a>
           </div>
          </div>
         </div>