<?php
$z[0]=Array("field","",59,88);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\n              <li> <i class=\"ztpic\"><a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" target=\"_blank\"><img src=\"[field:litpic/]\"></a></i> <b>[field:title/]</b><a href=\"\" target=\"_blank\" class=\"readmore\"><span>[field:pubdate function=\"MyDate('Y年m月d日 ',@me)\"/]</span></a> </li>\n              ",123,521);
$z[1][4]=array();
$z[1][4]['row']="6";
$z[1][4]['titlelen']="80";

?>