<article class="app-list sb clearfix">
        <figure class="figure fl"> <a class="thumbnail" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]"> <img class="img-cover br" src="[field:litpic /]" alt="[field:title /]" title="[field:title /]"> </a> </figure>
        <div class="content fl">
          <h2 class="title ellipsis"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">[field:title /]</a></h2>
          <p class="intro ellipsis">[field:description /]... </p>
          <p class="data clearfix">
            <time class="time fl"> <i class="iconfont icon-time"></i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
            <span class="view fl hidden-sm-md-lg"><i class="iconfont icon-view"></i>[field:click /]</span> </p>
        </div>
        <p class="btn fr"><a rel="nofollow" class="download transition br" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">立即查看</a></p>
      </article>