<?php
$z[0]=Array("field","",173,202);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",261,289);
$z[1][4]=array();
$z[1][4]['name']="typedir";
$z[2]=Array("arclist","\r\n        <li><span class=\"date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><i>1</i><a href=\"/zixun/153.html\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></li>\r\n        ",369,614);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['row']="10";

?>