<li class="pic">
                <figure class="thumbnail">
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">
                    <img src="[field:litpic/]" alt="[field:title/]" /></a>
                </figure>
                <p>
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a></p>
              </li>