<article class="post-list wow fadeInDown" id="list2">
            <div class="post-item-box goods-box">
              <div class="post-img-wp">
                <a href="/jianzhan/167.html" target="_blank">
                  <img class="goods-img" src="[field:litpic/]" alt="内容页面插入带权限的会员下载还有正文同时存在" /></a>
              </div>
              <div class="post-user-info">
                <a>
                  <span class="post-username">admin</span>
                  <span class="post-fbtime">2020-09-12</span></a>
              </div>
              <div class="post-title">
                <h3>
                  <a href="/jianzhan/167.html" title="内容页面插入带权限的会员下载还有正文同时存在" target="_blank">内容页面插入带权限的会员下载还有正文同时存在</a></h3>
              </div>
              <div class="post-item-meta">
                <a class="post-item-catename" href="/jianzhan/">
                  <i class="fa fa-columns"></i>大数据</a>
                <span class="post-item-viewnums">
                  <i class="fa fa-eye"></i>86次</span>
              </div>
            </div>
          </article>