<li class="item">
                <div class="item-img">
                    <a class="item-img-inner" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank">
                        <img class="j-lazy" src="[field:litpic/]" data-original="[field:litpic/]" width="480" height="300" alt="[field:title/]">
                    </a>
                    <a class="item-category" href="/a/fenxiang/" target="_blank">分享</a> </div>
                <div class="item-content">
                    <h2 class="item-title">
                        <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank"> [field:title/] </a>
                    </h2>
                    <div class="item-excerpt">
                        <p>&nbsp;  爆火带动了多少网红一夜爆火，给很多普通人带来了新的表达方式，多少产品莫名被抖音带火，让很多自媒体和企业...</p>
                    </div>
                    <div class="item-meta">
                        <span class="item-meta-li date"></span>
                        <span class="item-meta-li views" title="[field:title/]">
                            <i class="fa fa-eye"></i> 7
                        </span>
                    </div>
                </div>
            </li>