<article class="item fl">
            <a class="thumbnail" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]"> <img class="img-cover br" src="[field:litpic /]" alt="[field:title /]" title="[field:title /]">
                <div class="absolute">
                    <p class="p-title ellipsis">[field:title /]</p>
                </div>
                <i class="mask br"></i> </a>
        </article>