<?php
$z[0]=Array("typedir","",34,51);
$z[0][4]=array();
$z[1]=Array("pubdate","",52,97);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",98,110);
$z[2][4]=array();
$z[3]=Array("title","",124,138);
$z[3][4]=array();
$z[4]=Array("litpic","",221,236);
$z[4][4]=array();
$z[5]=Array("title","",243,257);
$z[5][4]=array();
$z[6]=Array("title","",343,357);
$z[6][4]=array();

?>