<li>
                    <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">
                        <div class="img">
                            <img src="[field:litpic/]" alt="[field:title/]" /></div>
                        <div class="info">
                            <h3>[field:title/]</h3>
                            <p></p>
                        </div>
                    </a>
                </li>