<li>
          <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank">
            <i><img src="http://192.168.1.16:8009/uploads/allimg/220721/094P62535-0-lp.jpg" alt="[field:title/]"></i><em>1</em>
            <h2>[field:title/]</h2>
            <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
          </a>
        </li>