<article class="newsitem">
            <figure class="thumbnail">
              <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">
                <img src="[field:litpic/]" alt="[field:title /]" /></a>
            </figure>
            <div class="info">
              <h2>
                <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">[field:title /]</a></h2>
              <div class="meta">
                <span>
                  <time datetime="2019-02-16">
                    <i class="far fa-calendar-alt"></i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
                </span>
                <span class="cat">
                  <i class="fas fa-columns"></i>
                  <a href="[field:typedir /]" title="[field:typename /]" target="_blank">[field:typename /]</a></span>
                <span><i class="fas fa-fire"></i>[field:click /]</span>
              </div>
              <p>　　[field:description /]...</p>
            </div>
          </article>