<?php
$z[0]=Array("typedir","",13,30);
$z[0][4]=array();
$z[1]=Array("pubdate","",31,76);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",77,89);
$z[2][4]=array();
$z[3]=Array("title","",103,117);
$z[3][4]=array();
$z[4]=Array("litpic","",129,144);
$z[4][4]=array();
$z[5]=Array("title","",151,165);
$z[5][4]=array();
$z[6]=Array("title","",177,191);
$z[6][4]=array();

?>