<?php
$z[0]=Array("typedir","",72,89);
$z[0][4]=array();
$z[1]=Array("pubdate","",90,135);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",136,148);
$z[2][4]=array();
$z[3]=Array("litpic","",206,221);
$z[3][4]=array();
$z[4]=Array("title","",295,309);
$z[4][4]=array();
$z[5]=Array("pubdate","",405,460);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y年m月d日 ',@me)";

?>