<?php
$z[0]=Array("typedir","",43,60);
$z[0][4]=array();
$z[1]=Array("pubdate","",61,106);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",107,119);
$z[2][4]=array();
$z[3]=Array("pubdate","",194,237);
$z[3][4]=array();
$z[3][4]['function']="MyDate('d',@me)";
$z[4]=Array("pubdate","",261,304);
$z[4][4]=array();
$z[4][4]['function']="MyDate('m',@me)";
$z[5]=Array("title","",357,371);
$z[5][4]=array();

?>