<li class="con">
                <div class="info"> <span class="sn"><a href="[field:typedir /]/" class="mcolor">[field:typename /]</a></span> </div>
                <div class="des"> <a class="h2" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">[field:title /]</a><img class="img br img-cover" src="{dede:global.cfg_cmspath/}/public/img/902e43f98d1a03335cccb49bc9380a4f.jpg" alt="回首2015，十位大佬眼中的2016或未来的创业趋势">
                    <div class="text">
                        <p>[field:description /]...</p>
                        <p class="data"> <span class="time">
                            <i class="fa fa-clock-o"></i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                            <span class="view"><i class="fa fa-eye"></i>[field:click /]</span>
                        </p>
                    </div>
                </div>
                <a href="/cyzx/2019-11-19/549.html" title="测试一个没有标题图片也没有内容图片的文章" class="more" target="_blank" rel="nofollow">详细阅读<i class="fa fa-angle-right"></i></a> </li>