<?php
$z[0]=Array("typedir","",13,30);
$z[0][4]=array();
$z[1]=Array("pubdate","",31,76);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",77,89);
$z[2][4]=array();
$z[3]=Array("title","",103,118);
$z[3][4]=array();
$z[4]=Array("litpic","",165,181);
$z[4][4]=array();
$z[5]=Array("title","",188,203);
$z[5][4]=array();
$z[6]=Array("global"," @me; ",213,278);
$z[6][4]=array();
$z[6][4]['name']="autoindex";
$z[6][4]['runphp']="yes";
$z[7]=Array("title","",303,318);
$z[7][4]=array();
$z[8]=Array("pubdate","",345,392);
$z[8][4]=array();
$z[8][4]['function']="MyDate('Y-m-d',@me)";

?>