<article class="article-list sb clearfix">
            <figure class="figure fl br"> <a class="thumbnail" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]"> <img class="img-cover br" src="[field:litpic /]" alt="[field:title /]" title="[field:title /]"></a> </figure>
            <div class="content">
                <h2 class="title ellipsis m-multi-ellipsis"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">[field:title /]</a></h2>
                <p class="intro hidden-sm">[field:description /]...</p>
                <p class="data clearfix"> <a class="cate fl br" href="[field:typedir /]/" target="_blank">
                    <i class="iconfont icon-cate"></i>[field:typename /]</a> <span class="hidden-sm-md-lg author fl">
                    <span class="hidden-sm-md-lg view fl font-oswald"> <i class="iconfont icon-view"></i>[field:click /]</span>
                    <time class="time fl font-oswald" datetime="[field:pubdate function="MyDate('Y-m-d',@me)"/]" title="[field:pubdate function="MyDate('Y-m-d',@me)"/]"> <i class="iconfont icon-time"></i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
                </p>
            </div>
        </article>