<?php
$z[0]=Array("typedir","",31,48);
$z[0][4]=array();
$z[1]=Array("pubdate","",49,94);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",95,107);
$z[2][4]=array();
$z[3]=Array("title","",121,135);
$z[3][4]=array();
$z[4]=Array("title","",234,248);
$z[4][4]=array();
$z[5]=Array("pubdate","",311,366);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y年m月d日 ',@me)";
$z[6]=Array("typedir","",387,403);
$z[6][4]=array();
$z[7]=Array("typename","",406,423);
$z[7][4]=array();

?>