<div id="con_one_{dede:global name='itemindex' runphp='yes'} @me=@me+1;{/dede:global}" style="display:none;">
              {dede:arclist titlelen='80' row='10'}
              <div class="post">
                <h2>
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank" rel="bookmark">[field:title/]</a></h2>
                <h6>[field:pubdate function="MyDate('Y-m-d ',@me)"/] | 栏目：<a href='[field:typedir/]'>[field:typename/]</a>| 浏览:[field:click/]<div class="clear"></div></h6>
                <div class="intro">
                      <span id="img">
                        <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">
                          <img alt="[field:title/]" src="[field:litpic/]" /></a>
                      </span>
                  <p>[field:description /]...</p>
                  </a>
                </div>
              </div>
              {/dede:arclist}
            </div>

            <section class="boxWrap">
              <div class="box">
                <div class="top">
                  <span><a href="#" title="{dede:field name='typename'/}">更多</a></span>
                  <h2>{dede:field name='typename'/}</h2>
                </div>
                <ul>
                  {dede:arclist titlelen='80' row='1'}
                  <li class="first">
                    <figure class="thumbnail">
                      <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank" title="[field:title/]">
                        <img src="[field:litpic/]" alt="[field:title/]" /></a>
                    </figure>
                    <div class="info">
                      <h4>
                        <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank" title="[field:title/]">[field:title/]</a></h4>
                      <p>[field:description /]...</p>
                    </div>
                  </li>
                  {/dede:arclist}
                  <li class="list">
                    <h4>
                      <a href="/zixun/153.html" target="_blank" title="国外机构测得iPhone 11 Pro辐射量超标137%">国外机构测得iPhone 11 Pro辐射量超标137%</a></h4>
                  </li>
                  <li class="list">
                    <h4>
                      <a href="/zixun/152.html" target="_blank" title="买吗?苹果正设计全新iPhone!配屏下指纹">买吗?苹果正设计全新iPhone!配屏下指纹</a></h4>
                  </li>
                  <li class="list">
                    <h4>
                      <a href="/zixun/151.html" target="_blank" title="一代手机巨头就此落幕：粉丝唏嘘!">一代手机巨头就此落幕：粉丝唏嘘!</a></h4>
                  </li>
                  <li class="list">
                    <h4>
                      <a href="/zixun/150.html" target="_blank" title="三星预计2020年可售出250万部Galaxy Z Flip">三星预计2020年可售出250万部Galaxy Z Flip</a></h4>
                  </li>
                  <li class="list">
                    <h4>
                      <a href="/zixun/148.html" target="_blank" title="华为5G到底有多厉害?美国被逼要出这招了">华为5G到底有多厉害?美国被逼要出这招了</a></h4>
                  </li>
                  <li class="list">
                    <h4>
                      <a href="/zixun/147.html" target="_blank" title="iQOO 3 5G性能旗舰定档2月25日!通过线上直播发布">iQOO 3 5G性能旗舰定档2月25日!通过线上直播发布</a></h4>
                  </li>
                </ul>
              </div>
            </section>