<li class="infinitescroll_li">
                    <div class="img">
                        <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">
                            <img src="[field:litpic/]" alt="[field:title/]" /></a>
                    </div>
                    <div class="info">
                        <h3><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a></h3>
                        <p></p>
                        <span>日期：[field:pubdate function="MyDate('Y年m月d日 ',@me)"/]    分类：<a href="/[field:typedir/]/" title="[field:typename/]">[field:typename/]</a></span>
                    </div>
                </li>