<?php
$z[0]=Array("arclist","\r\n                      <li><a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\"><img src=\"[field:litpic/]\"><span>[field:title/]</span></a></li>\r\n                      ",107,365);
$z[0][4]=array();
$z[0][4]['titlelen']="80";
$z[0][4]['row']="2";
$z[1]=Array("arclist","\r\n                  <li><i></i><a href=\"a/yunying/138.html\" title=\"6609首歌从KTV下架，《十年》《泡沫》均中\">6609首歌从KTV下架，《十年》《泡沫》均中</a>\r\n                      <p> 11月5日，一项热搜出现在邦哥的微博首页，并且排名一路蹿升至第一，挂在榜首直至今日凌晨：6000多首歌从KTV下架。...</p>\r\n                  </li>\r\n                  ",469,941);
$z[1][4]=array();
$z[1][4]['titlelen']="80";
$z[1][4]['limit']="2,5";

?>