<div class="newsitem">
              <div class="newspic">
                  <ul>
                      {dede:arclist titlelen='80' row='2'}
                      <li><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img src="[field:litpic/]"><span>[field:title/]</span></a></li>
                      {/dede:arclist}
                  </ul>
              </div>
              <ul class="newslist">
                  {dede:arclist titlelen='80' limit='2,5'}
                  <li><i></i><a href="a/yunying/138.html" title="6609首歌从KTV下架，《十年》《泡沫》均中">6609首歌从KTV下架，《十年》《泡沫》均中</a>
                      <p> 11月5日，一项热搜出现在邦哥的微博首页，并且排名一路蹿升至第一，挂在榜首直至今日凌晨：6000多首歌从KTV下架。...</p>
                  </li>
                  {/dede:arclist}

                  <li><i></i><a href="a/yunying/138.html" title="6609首歌从KTV下架，《十年》《泡沫》均中">6609首歌从KTV下架，《十年》《泡沫》均中</a>
                      <p> 11月5日，一项热搜出现在邦哥的微博首页，并且排名一路蹿升至第一，挂在榜首直至今日凌晨：6000多首歌从KTV下架。...</p>
                  </li>
                  <li><i></i><a href="a/yunying/139.html" title="雷军：天使投资人经历让我学会找风口">雷军：天使投资人经历让我学会找风口</a>
                      <p> 人工智能时代已来，雷军为小米找的下一个风口是什么？成立相机部门能干翻华为吗? ▲雷军在在故宫发布滑盖手机...</p>
                  </li>
                  <li><i></i><a href="a/yunying/140.html" title="互联网是我们孩子的哆啦A梦还是洪水猛兽">互联网是我们孩子的哆啦A梦还是洪水猛兽</a>
                      <p> 像众多新生儿父母一样，我快要崩溃了。我儿子 Oliver 两个半月了，正处于五官感受觉醒时，只要他醒着就可能受刺...</p>
                  </li>
                  <li><i></i><a href="a/yunying/67.html" title="区块链未死！2019区块链+农业或将浴火重">区块链未死！2019区块链+农业或将浴火重</a>
                      <p> 不在沉默中爆发，就在沉默中灭亡！ 这句话来形容当下的区块链。2018年疯狂的区块链因受政策监管与打压，资本、...</p>
                  </li>
                  <li><i></i><a href="a/yunying/145.html" title="金立手机16年：一杯敬国产手机第一名，">金立手机16年：一杯敬国产手机第一名，</a>
                      <p> 23日，媒体一篇《复盘金立死亡之谜》将金立困境公之于众，文章称，金立总资产和总负债分别为人民币201.2亿和28...</p>
                  </li>

              </ul>
          </div>