<?php
$z[0]=Array("typedir","",48,65);
$z[0][4]=array();
$z[1]=Array("pubdate","",66,111);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",112,124);
$z[2][4]=array();
$z[3]=Array("title","",138,152);
$z[3][4]=array();
$z[4]=Array("title","",194,208);
$z[4][4]=array();
$z[5]=Array("litpic","",240,255);
$z[5][4]=array();
$z[6]=Array("title","",262,276);
$z[6][4]=array();

?>