<?php
$z[0]=Array("field","",89,117);
$z[0][4]=array();
$z[0][4]['name']="typedir";
$z[1]=Array("field","",135,164);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                  <li class=\"first\"> <a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" title=\"[field:title/]\" class=\"pic\"> <img class=\"img-cover br\" src=\"[field:litpic/]\" alt=\"[field:title/]\" title=\"[field:title/]\"> </a> <a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" title=\"[field:title/]\" class=\"text\">[field:title/]</a>\r\n                      <div class=\"des\"> [field:description/]</div>\r\n                  </li>\r\n                  ",235,810);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['row']="1";

?>