<article class="item">
                  <div class="clearfix"> <a class="thumbnail fl" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]"> <img class="img img-cover br" src="[field:litpic/]" alt="[field:title/]" title="[field:title/]"> </a>
                      <div class="fr-wrap">
                          <div class="title-wrap">
                              <h2 class="title ellipsis"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a> </h2>
                              <p class="intro br clearfix ellipsis"> &nbsp;&nbsp;&nbsp;&nbsp;ps：[field:description/]... </p>
                          </div>
                      </div>
                  </div>
              </article>