<?php
$z[0]=Array("typedir","",52,69);
$z[0][4]=array();
$z[1]=Array("pubdate","",70,116);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y/md',@me)";
$z[2]=Array("id","",117,129);
$z[2][4]=array();
$z[3]=Array("title","",143,158);
$z[3][4]=array();
$z[4]=Array("litpic","",205,221);
$z[4][4]=array();
$z[5]=Array("title","",228,243);
$z[5][4]=array();
$z[6]=Array("title","",270,285);
$z[6][4]=array();

?>