<p class="c-title"> <span>[field:typename /]</span> <a class="more" href="[field:typedir /]/" title="更多[field:typename /]">更多</a> </p>
            <article class="item top">
                <h2 class="top-title ellipsis"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">[field:title /]</a></h2>
                <p class="intro multi-ellipsis"> <i class="iconfont icon-yin"></i> [field:description /]... </p>
            </article>