<li>
                <a href="" target="_blank">
                <img class="j-lazy" src="" data-original="[field:litpic/]" alt="[field:title/]">
                </a>
                <span>[field:title/]</span>
            </li>

            <li class="item">
                <div class="item-img"> <a class="item-img-inner" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]"> <img class="j-lazy" src="[field:litpic/]" data-original="[field:litpic/]" width="480" height="300" alt="[field:title/]"> </a> </div>
                <div class="item-content">
                    <p class="item-title"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a></p>
                    <p class="item-date">2020年03月20日</p>
                </div>
            </li>