<li class="item">
                <div class="item-img">
                    <a class="item-img-inner" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank">
                        <img class="j-lazy" src="[field:litpic/]" data-original="[field:litpic/]" width="480" height="300" alt="[field:title/]">
                    </a>
                    <a class="item-category" href="[field:typedir/]" target="_blank">[field:typename/]</a>
                </div>
                <div class="item-content">
                    <h2 class="item-title"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank"> [field:title/] </a> </h2>
                    <div class="item-excerpt">
                        <p>[field:description/]</p>
                    </div>
                    <div class="item-meta">
                        <span class="item-meta-li date"></span>
                        <span class="item-meta-li views" title="[field:title/]">
                            <i class="fa fa-eye"></i> [field:click/]
                        </span>
                    </div>
                </div>
            </li>