<?php
$z[0]=Array("typedir","",29,46);
$z[0][4]=array();
$z[1]=Array("pubdate","",47,92);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",93,105);
$z[2][4]=array();
$z[3]=Array("title","",119,133);
$z[3][4]=array();
$z[4]=Array("litpic","",163,178);
$z[4][4]=array();
$z[5]=Array("title","",185,199);
$z[5][4]=array();
$z[6]=Array("title","",229,243);
$z[6][4]=array();

?>