<div class="newsitem">
              <div class="newspic">
                  <ul>
                      {dede:arclist titlelen='80' row='2'}
                      <li><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img src="[field:litpic/]"><span>[field:title/]</span></a></li>
                      {/dede:arclist}
                  </ul>
              </div>
              <ul class="newslist">
                  {dede:arclist titlelen='80' limit='2,5'}
                  <li><i></i><a href="a/yunying/138.html" title="6609首歌从KTV下架，《十年》《泡沫》均中">6609首歌从KTV下架，《十年》《泡沫》均中</a>
                      <p>[field:description /]...</p>
                  </li>
                  {/dede:arclist}
              </ul>
          </div>