<?php
$z[0]=Array("litpic","",54,69);
$z[0][4]=array();
$z[1]=Array("typedir","",101,118);
$z[1][4]=array();
$z[2]=Array("pubdate","",119,164);
$z[2][4]=array();
$z[2][4]['function']="MyDate('Ymd',@me)";
$z[3]=Array("id","",165,177);
$z[3][4]=array();
$z[4]=Array("title","",191,205);
$z[4][4]=array();
$z[5]=Array("title","",252,266);
$z[5][4]=array();
$z[6]=Array("title","",313,327);
$z[6][4]=array();

?>