<?php
$z[0]=Array("field","",28,56);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",58,87);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","    <ul class='autod'>\n              <li><a href=\"[field:arcurl /]\">[field:title /]</a></li>\n              <li>([field:pubdate function=\"MyDate('m-d',@me)\"/])</li>\n          </ul>\n              ",126,372);
$z[2][4]=array();
$z[2][4]['titlelen']="42";
$z[2][4]['row']="10";

?>