<li>
                  <figure class="thumbnail">
                    <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank" title="[field:title/]">
                      <img src="[field:litpic/]" alt="[field:title/]" /></a>
                  </figure>
                  <h3>
                    <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank" title="[field:title/]">[field:title/]</a></h3>
                </li>