<div class="col-md-4 col-xs-6  th_padding">
         <div class="thliorder1">
          <div class="gundongimg">
           <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]"><img class="th-img gundong-img-height" src="[field:litpic /]" /></a>
          </div>
          <div class="daodu">
           <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a>
          </div>
          <div class="daoducon">
           <p>[field:description /]...</p>
          </div>
          <div class="thinfo">
           时间：[field:pubdate function="MyDate('Y-m-d',@me)"/]&nbsp;&nbsp;阅读：[field:click/]
          </div>
         </div>
        </div>