<li>
          <span class="blogpic imgscale"><i><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"></a></i><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title=""><img src="[field:litpic/]" alt=""></a></span>
          <p class="blogtext"><h3 class="blogtitle"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank">[field:title/]</a></h3></p>
          <p class="bloginfo"><span>[field:pubdate function="MyDate('Y年m月d日 ',@me)"/]</span></p>
        </li>