<li>
            <div class="recent-posts-img"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img src="[field:litpic/]" class="thumbnail" alt="[field:title/]"></a></div>
            <div class="recent-posts-title">
                <h4 class="tit"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">[field:title/]</a></h4>
                <span class="info"><i class="iconfont icon-yanjing1"></i> [field:click/]</span> </div>
        </li>