<li>
                <div class="pic"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img src="[field:litpic /]" alt="[field:title /]"></a></div>
                <h3><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">[field:title /]</a></h3>
                <p>[field:description /]...</p>
                <div class="info">
                    <span><i class="iconfont">&#xe675;</i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                    <span><i class="iconfont">&#xe6e2;</i>[field:click /]浏览量</span>
                    <span><i class="iconfont">&#xe7f8;</i><a href="[field:typedir /]/">[field:typename /]</a></span>
                </div>
            </li>