<article class="post-list wow fadeInDown" id="list2">
            <div class="post-item-box goods-box">
              <div class="post-img-wp">
                <a href="[field:typedir /]/15/[field:id /].html" target="_blank">
                <img class="goods-img" src="[field:litpic/]" alt="[field:title/]" /></a>
              </div>
              <div class="post-user-info">
                <a><span class="post-fbtime">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></a>
              </div>
              <div class="post-title">
                <h3>
                  <a href="[field:typedir /]/15/[field:id /].html" title="[field:title/]" target="_blank">[field:title/]</a></h3>
              </div>
              <div class="post-item-meta">
                <a class="post-item-catename" href="[field:typedir /]/">
                  <i class="fa fa-columns"></i>[field:typename /]</a>
                <span class="post-item-viewnums">
                  <i class="fa fa-eye"></i>[field:click /]次</span>
              </div>
            </div>
          </article>