<?php
$z[0]=Array("typedir","",57,74);
$z[0][4]=array();
$z[1]=Array("pubdate","",75,120);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",121,133);
$z[2][4]=array();
$z[3]=Array("litpic","",150,165);
$z[3][4]=array();
$z[4]=Array("title","",190,204);
$z[4][4]=array();
$z[5]=Array("title","",329,343);
$z[5][4]=array();
$z[6]=Array("click","",428,442);
$z[6][4]=array();

?>