<?php
$z[0]=Array("typename","",66,83);
$z[0][4]=array();
$z[1]=Array("typedir","",229,246);
$z[1][4]=array();
$z[2]=Array("pubdate","",247,292);
$z[2][4]=array();
$z[2][4]['function']="MyDate('Ymd',@me)";
$z[3]=Array("id","",293,305);
$z[3][4]=array();
$z[4]=Array("litpic","",338,353);
$z[4][4]=array();
$z[5]=Array("title","",367,381);
$z[5][4]=array();
$z[6]=Array("pubdate","",435,490);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y年m月d日 ',@me)";

?>