<p class="c-title mb10"> <span>[field:typename /]</span> <a class="more" href="[field:typedir /]/" title="更多[field:typename /]">更多</a> </p>
              <article class="item mb10"> <a class="thumbnail" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]"> <img class="img-cover br" src="[field:litpic /]" alt="[field:title /]" title="[field:title /]">
                  <div class="absolute">
                      <p class="p-title ellipsis">[field:title /]</p>
                  </div>
                  <i class="mask br"></i> </a>
              </article>