<li class="infinitescroll_li">
                    <div class="img">
                        <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">
                            <img src="[field:litpic/]" alt="内容页面插入带权限的会员下载还有正文同时存在" /></a>
                    </div>
                    <div class="info">
                        <h3><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a></h3>
                        <p></p>
                        <span>日期：[field:pubdate function="MyDate('Y/m/d ',@me)"/]&nbsp;&nbsp;&nbsp;&nbsp;分类：<a href="[field:typedir/]/" title="[field:typename/]">[field:typename/]</a></span>
                    </div>
                </li>