<?php
$z[0]=Array("typedir","",97,114);
$z[0][4]=array();
$z[1]=Array("pubdate","",115,160);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",161,173);
$z[2][4]=array();
$z[3]=Array("typedir","",472,489);
$z[3][4]=array();
$z[4]=Array("pubdate","",490,535);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Ymd',@me)";
$z[5]=Array("id","",536,548);
$z[5][4]=array();

?>