<?php
$z[0]=Array("typedir","",59,76);
$z[0][4]=array();
$z[1]=Array("pubdate","",77,122);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",123,135);
$z[2][4]=array();
$z[3]=Array("litpic","",152,167);
$z[3][4]=array();
$z[4]=Array("title","",192,206);
$z[4][4]=array();
$z[5]=Array("title","",333,347);
$z[5][4]=array();
$z[6]=Array("click","",432,446);
$z[6][4]=array();

?>