<li>
            <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">
              <time class="l">
                <span class="hot_li_data">
                  <em>[field:pubdate function="MyDate('d',@me)"/]</em>[field:pubdate function="MyDate('Y-m',@me)"/]</span></time>
              <h3>[field:title/]</h3>
              <p class="hot_li_ms">[field:description /]...</p></a>
          </li>