<li>
                <figure class="thumbnail">
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank" title="[field:title/]">
                    <img src="[field:litpic/]" alt="[field:title/]" /></a>
                </figure>
                <h3>
                  <a href="/dianshang/157.html" target="_blank" title="iPhone 9现身韩国电信零售店预约海报">iPhone 9现身韩国电信零售店预约海报</a></h3>
              </li>