<li>
                    <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">
                        <div class="img">
                            <img src="[field:litpic/]" alt="[field:title/]" /></div>
                        <div class="info">
                            <h3>[field:title/]</h3>
                            <p>[field:pubdate function="MyDate('Y年m月d日 ',@me)"/]　</p>
                        </div>
                    </a>
                </li>