<?php
$z[0]=Array("typedir","",35,52);
$z[0][4]=array();
$z[1]=Array("pubdate","",53,98);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",99,111);
$z[2][4]=array();
$z[3]=Array("litpic","",201,216);
$z[3][4]=array();
$z[4]=Array("title","",223,237);
$z[4][4]=array();
$z[5]=Array("title","",325,339);
$z[5][4]=array();
$z[6]=Array("pubdate","",377,432);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y年m月d日 ',@me)";

?>