<div class="swiper-slide">
              <div class="thslidelist gundongimg ">
                <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" class="silde_a_border"> <img class="th-img thslide2-img-height" src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /> </a>
                <div class="thslidetitle">
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a>
                </div>
              </div>
            </div>

            <article class="mx3-hentry nba">
              <figure class="mx3-thumbnail">
                <a href="/zixun/153.html">
                  <img src="{dede:global.cfg_cmspath/}/public/img/1bed23fb41166bdec133a4ea723068b9.jpg" width="103" height="78" alt="国外机构测得iPhone 11 Pro辐射量超标137%"></a>
              </figure>
              <header class="mx3-header">
                <h2 class="mx3-entry-title">
                  <a href="/zixun/153.html" title="国外机构测得iPhone 11 Pro辐射量超标137%" rel="bookmark">国外机构测得iPhone 11 Pro辐射量超标137%</a></h2>
              </header>
              <div class="mx3-entry-content">
                <span class="mx3-entry-meta">
                  <span class="mx3-date">
                    <i class="fa fa-calendar"></i>02/08</span>
                  <span class="mx3-views">
                    <i class="fa fa-eye"></i>5750</span>
                  <span class="mx3-comment">
                    <a href="/zixun/153.html#comments" rel="mx3-external-nofollow">
                      <i class="fa fa-comment"></i>1</a>
                  </span>
                </span>
              </div>
            </article>