<div class="col-md-4 col-xs-6  th_padding">
         <div class="thliorder1">
          <div class="gundongimg">
           <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]"><img class="th-img gundong-img-height" src="{dede:global.cfg_templets_skin/}/static/img/c602e4f5d792e64a020e455a20d2a2e8.jpg" /></a>
          </div>
          <div class="daodu">
           <a href="/dianshang/157.html" title="[field:title/]">[field:title/]</a>
          </div>
          <div class="daoducon">
           <p>　　iPhone 9现身韩国电信零售店预约海报　　2020-02-06 12:50:42　来源: 威锋网　　韩国电信(KT)某零售门店已经现已开启预约 Galaxy S20系列送 Galaxy Buds+ 活...</p>
          </div>
          <div class="thinfo">
           时间：[field:pubdate function="MyDate('Y-m-d',@me)"/]&nbsp;&nbsp;阅读：[field:click/] ℃
          </div>
         </div>
        </div>