<?php
$z[0]=Array("typedir","",31,48);
$z[0][4]=array();
$z[1]=Array("pubdate","",49,94);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",95,107);
$z[2][4]=array();
$z[3]=Array("litpic","",140,155);
$z[3][4]=array();
$z[4]=Array("title","",169,183);
$z[4][4]=array();
$z[5]=Array("pubdate","",237,292);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y年m月d日 ',@me)";

?>