<li class="con">
                <div class="info"> <span class="sn"><a href="[field:typedir /]/" class="mcolor">[field:typename /]</a></span> </div>
                <div class="des">
                  <a class="h2" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">[field:title /]</a>
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]" class="pic"> <img class="img br img-cover" src="[field:litpic /]" alt="[field:title /]"> </a>
                  <div class="text">
                    <p>[field:description /]...</p>
                    <p class="data"> <span class="time">
                            <i class="fa fa-clock-o"></i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                      <span class="view"><i class="fa fa-eye"></i>[field:click /]</span>
                    </p>
                  </div>
                </div>
                <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]" class="more" target="_blank" rel="nofollow">详细阅读<i class="fa fa-angle-right"></i></a> </li>