<li><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">[field:title/]</a></li>
              <li class="list clearfix"><span class="avatar fl"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img src="[field:litpic/]" alt="[field:title/]" title="[field:title/]"></a></span>
                  <div class="title"><a class="a ellipsis" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="查阅详情">[field:title/]</a>
                      <div class="info ellipsis"><span class="time"><i class="iconfont icon-time"></i>05-29</span><span class="author"><i class="iconfont icon-user"></i>[field:click/] </span></div>
                  </div>
              </li>