<?php
$z[0]=Array("typename","",66,83);
$z[0][4]=array();
$z[1]=Array("typedir","",232,249);
$z[1][4]=array();
$z[2]=Array("pubdate","",250,295);
$z[2][4]=array();
$z[2][4]['function']="MyDate('Ymd',@me)";
$z[3]=Array("id","",296,308);
$z[3][4]=array();
$z[4]=Array("litpic","",341,356);
$z[4][4]=array();
$z[5]=Array("title","",370,384);
$z[5][4]=array();
$z[6]=Array("pubdate","",438,493);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y年m月d日 ',@me)";

?>