<li>
                        <div class="sideshow"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_ablank"  title="[field:title/]"> <img width='80' height='60' src='[field:litpic/]' class='icon wp-post-image' alt='[field:title/]' title='[field:title/]' /> </a>
                            <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_ablank"  title="[field:title/]"> [field:title/]</a>
                            <span class="datetime"> [field:pubdate function="MyDate('Y年m月d日',@me)"/] </span> </div>
                    </li>