<li class="first">
                    <figure class="thumbnail">
                      <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank" title="[field:title/]">
                        <img src="[field:litpic/]" alt="[field:title/]" /></a>
                    </figure>
                    <div class="info">
                      <h4>
                        <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank" title="[field:title/]">[field:title/]</a></h4>
                      <p>[field:description /]...</p>
                    </div>
                  </li>