<div class="hotnewlist"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank">
            <div class="hotdiv" style="background-image:url([field:litpic/])">
                <div class="overlay"></div>
                <div class="title"><span>[field:typename /]</span>
                    <h3>[field:title /]</h3>
                </div>
            </div>
        </a> </div>