<li class="blogs_list"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank"><i><img src="[field:litpic /]" alt="[field:title /]"></i>
              <h2>[field:title /]</h2></a>
              <p>[field:description /]...</p>
              <div class="blogs_writer">[field:click /]<span class="blogs_time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></div>
              <div class="blogs_tags"><a href='[field:typedir /]' target='_blank'>[field:typename /]</a></div>
              <span class="blogs_lm"><a href="[field:typedir /]" target="_blank">[field:typename /]</a></span>
          </li>