<div class="post">
      <h2>
       <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank" rel="bookmark">[field:title/]</a></h2>
      <h6>[field:pubdate function="MyDate('Y-m-d ',@me)"/] | 栏目：<a href='[field:typedir/]'>[field:typename/]</a>| 浏览:[field:click/]<div class="clear"></div></h6>
      <div class="intro">
                      <span id="img">
                        <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">
                          <img alt="[field:title/]" src="[field:litpic/]" /></a>
                      </span>
       <p>[field:description /]...</p>
       </a>
      </div>
     </div>
     
     <div class="col-md-4 col-xs-12  pc_margintop">
      <section>
       <div class="thleftcon" style="height:363px;">
        <div class="thleftbt thwenzhang">
         <span>资讯</span>
         <div class="listMore">
          <a href="/zixun/">More +</a>
         </div>
        </div>
        <ul class="th-5">
         <li><span class="date">02-08</span><i>1</i><a href="/zixun/153.html" title="国外机构测得iPhone 11 Pro辐射量超标137%" target="_blank">国外机构测得iPhone 11 Pro辐射量超标137%</a></li>
         <li><span class="date">02-08</span><i>2</i><a href="/zixun/152.html" title="买吗?苹果正设计全新iPhone!配屏下指纹" target="_blank">买吗?苹果正设计全新iPhone!配屏下指纹</a></li>
         <li><span class="date">02-08</span><i>3</i><a href="/zixun/151.html" title="一代手机巨头就此落幕：粉丝唏嘘!" target="_blank">一代手机巨头就此落幕：粉丝唏嘘!</a></li>
         <li><span class="date">02-08</span><i>4</i><a href="/zixun/150.html" title="三星预计2020年可售出250万部Galaxy Z Flip" target="_blank">三星预计2020年可售出250万部Galaxy Z Flip</a></li>
         <li><span class="date">02-08</span><i>5</i><a href="/zixun/148.html" title="华为5G到底有多厉害?美国被逼要出这招了" target="_blank">华为5G到底有多厉害?美国被逼要出这招了</a></li>
         <li><span class="date">02-08</span><i>6</i><a href="/zixun/147.html" title="iQOO 3 5G性能旗舰定档2月25日!通过线上直播发布" target="_blank">iQOO 3 5G性能旗舰定档2月25日!通过线上直播发布</a></li>
         <li><span class="date">02-08</span><i>7</i><a href="/zixun/146.html" title="OPPO Find X2真机图曝光 给我们的惊喜有这些" target="_blank">OPPO Find X2真机图曝光 给我们的惊喜有这些</a></li>
         <li><span class="date">02-08</span><i>8</i><a href="/zixun/23.html" title="500元超好用蓝牙耳机 运动型无线蓝牙耳机" target="_blank">500元超好用蓝牙耳机 运动型无线蓝牙耳机</a></li>
        </ul>
       </div>
      </section>
     </div>