<?php
$z[0]=Array("click","",23,37);
$z[0][4]=array();
$z[1]=Array("global","@me=@me+1;[/field: global]</i><a href=\"[field:typedir ",47,145);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("pubdate","",146,191);
$z[2][4]=array();
$z[2][4]['function']="MyDate('Ymd',@me)";
$z[3]=Array("id","",192,204);
$z[3][4]=array();
$z[4]=Array("title","",218,232);
$z[4][4]=array();
$z[5]=Array("title","",237,251);
$z[5][4]=array();

?>