<?php
$z[0]=Array("click","",23,37);
$z[0][4]=array();
$z[1]=Array("global"," @me=@me+1; ",47,116);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("typedir","",129,146);
$z[2][4]=array();
$z[3]=Array("pubdate","",147,192);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Ymd',@me)";
$z[4]=Array("id","",193,205);
$z[4][4]=array();
$z[5]=Array("title","",219,233);
$z[5][4]=array();
$z[6]=Array("title","",238,252);
$z[6][4]=array();

?>