<article class="mx3-hentry nba">
              <figure class="mx3-thumbnail">
                <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">
                  <img src="[field:litpic/]" width="103" height="78" alt="[field:title/]"></a>
              </figure>
              <header class="mx3-header">
                <h2 class="mx3-entry-title">
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" rel="bookmark">[field:title/]</a></h2>
              </header>
              <div class="mx3-entry-content">
                <span class="mx3-entry-meta">
                  <span class="mx3-date">
                    <i class="fa fa-calendar"></i>[field:pubdate function="MyDate('m/d',@me)"/]</span>
                  <span class="mx3-views"><i class="fa fa-eye"></i>[field:click/]</span>
                </span>
              </div>
            </article>