<div class="wapost card">
              <h2 class="multi-ellipsis"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:click /]">[field:click /]</a> </h2>
              <p class="img"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank"> <img class="img-cover br" src="[field:litpic /]" alt="[field:click /]" title="[field:click /]"> </a> </p>
              <p class="text">[field:click /]</p>
              <div class="count"> <span><i class="fa fa-eye"></i>[field:click /]</span>
                  <span class="edit"><i class="fa fa-clock-o"></i>[field:pubdate function="MyDate('Y-m-d',@me)"/] </span> </div>
          </div>