<div class="items">
                <div class="content-box">
                    <div class="posts-gallery-img"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img class="thumbnail" src="[field:litpic/]" alt="[field:title/]"></a> </div>
                    <div class="posts-gallery-content">
                        <h2><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank">[field:title/]</a></h2>
                        <div class="posts-gallery-text">[field:title/]...</div>
                        <div class="posts-default-info posts-gallery-info">
                            <ul>
                                <li class="ico-cat"><i class="iconfont icon-liebiao"></i> <a href="[field:typedir/]" target="_blank">[field:typename/]</a></li>
                                <li class="ico-time"><i class="iconfont icon-iconfontshijian"></i> [field:pubdate function="MyDate('Y-m-d ',@me)"/]</li>
                                <li class="ico-eye"><i class="iconfont icon-yanjing1"></i> [field:click/]</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>