<h2>
                <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank" rel="bookmark">
                  <span class="jinrituijian">推荐阅读</span>[field:title/]
                </a>
              </h2>
              <h6>[field:pubdate function="MyDate('Y年m月d日 ',@me)"/] | 栏目：<a href='[field:typedir/]/'>[field:typename/]</a>| 浏览:[field:click/]<div class="clear"></div></h6>
              <div class="intro">
                <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank" rel="bookmark">
                  <p>[field:description /]...</p>
                </a>
                <br /></div>