<div class="col-md-4 col-xs-6 ">
         <div class="thliorder1">
          <div class="thliorder1_title">
           <span><a href="[field:typedir /]/" title="[field:typename /]">[field:typename /]</a></span>
           <div class="thtime">[field:pubdate function="MyDate('m-d',@me)"/]          </div>
          </div>
          <div class="daodu">
           <a href="field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a>
          </div>
          <div class="daoducon">
           <p>[field:description /]...</p>
          </div>
         </div>
        </div>