<?php
$z[0]=Array("global"," @me=@me+1;",17,85);
$z[0][4]=array();
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arclist","\r\n              <div class=\"post\">\r\n                <h2>\r\n                  <a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" title=\"[field:title/]\" target=\"_blank\" rel=\"bookmark\">[field:title/]</a></h2>\r\n                <h6>[field:pubdate function=\"MyDate('Y-m-d ',@me)\"/] | 栏目：<a href='[field:typedir/]'>[field:typename/]</a>| 浏览:[field:click/]<div class=\"clear\"></div></h6>\r\n                <div class=\"intro\">\r\n                      <span id=\"img\">\r\n                        <a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" title=\"[field:title/]\">\r\n                          <img alt=\"[field:title/]\" src=\"[field:litpic/]\" /></a>\r\n                      </span>\r\n                  <p>[field:description /]...</p>\r\n                  </a>\r\n                </div>\r\n              </div>\r\n              ",125,1072);
$z[1][4]=array();
$z[1][4]['titlelen']="80";
$z[1][4]['row']="10";
$z[2]=Array("field","",1246,1275);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",1318,1347);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("arclist","\r\n                  <li class=\"first\">\r\n                    <figure class=\"thumbnail\">\r\n                      <a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" target=\"_blank\" title=\"[field:title/]\">\r\n                        <img src=\"[field:litpic/]\" alt=\"[field:title/]\" /></a>\r\n                    </figure>\r\n                    <div class=\"info\">\r\n                      <h4>\r\n                        <a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n                      <p>[field:description /]...</p>\r\n                    </div>\r\n                  </li>\r\n                  ",1418,2197);
$z[4][4]=array();
$z[4][4]['titlelen']="80";
$z[4][4]['row']="1";
$z[5]=Array("arclist","\r\n                  <li class=\"list\">\r\n                    <h4><a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n                  </li>\r\n                  ",2219,2536);
$z[5][4]=array();
$z[5][4]['titlelen']="80";
$z[5][4]['limit']="1,6";

?>