<li class="side-list side-list-box">
              <a href="[field:typedir /]/15/[field:id /].html" title="[field:title/]" class="block">
                <img src="[field:litpic/]" alt="[field:title/]" class="kandyCover wi7 hi7 flol amar" width="112" height="112" style="background: url([field:litpic/]) center center / cover no-repeat;"></a>
              <div class="side-h3-title">
                <h3>
                  <a href="[field:typedir /]/15/[field:id /].html" title="[field:title/]">[field:title/]</a></h3>
                <small>[field:pubdate function="MyDate('Y-m',@me)"/]</small>...</div>
              <p class="">
                <a href="[field:typedir /]/15/[field:id /].html" title="[field:title/]">[field:description /]...</a></p>
            </li>