<div class="block">
          <h2>
                    <span class="category">
                        <a href="[field:typedir/]" rel="category tag" >[field:typename/]</a><i class="fa fa-caret-right"></i>
                    </span>
              <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"  target="_ablank" >[field:title/]</a></h2>
          <div class="clear"></div>

          <div class='viewimg'> <a href='[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html' title='[field:title/]' target='_ablank' class='ipic'> <img src='[field:litpic/]' alt='[field:title/]' class='thumbnail' /><span class='shine' style='background-position: 160px 50%;'> </span></a> </div>

          <div class="preview"> [field:description /]...</div>
          <div class="preem">
              <span><i class="fa fa-clock-o"></i> [field:pubdate function="MyDate('Y年m月d日 ',@me)"/] </span>
              <span><i class="fa fa-eye"></i> [field:click/] </span><span> </span>
              <span class="more"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">阅读详情</a></span>
          </div>
      </div>