<div class="gtw-ul gclear">
                            <div class="gtw-img">
                                <a href="[field:typedir /]/[field:pubdate function="MyDate('Y/m-d',@me)"/]/[field:id /].html"><img src="[field:litpic/]" alt="[field:title/]" style="width: 240px;height: 150px;"></a>
                            </div>
                            <div class="gtw-body">
                                <a href="[field:typedir /]/[field:pubdate function="MyDate('Y/m-d',@me)"/]/[field:id /].html">
                                <h4>[field:title /]</h4>
                                </a>
                                <p>[field:description /]...</p>
                                <div class="gtw-sx">
                                    <i class="fa fa-clock-o" aria-hidden="true"> [field:pubdate function="MyDate('Y年m月d日 ',@me)"/]</i>
                                    <i class="fa fa-eye" aria-hidden="true"> [field:click/]</i>
                                    <a href="[field:typedir /]"><i class="fa fa-folder-open" aria-hidden="true"> [field:typename/]</i></a>
                                </div>
                            </div>
                        </div>