<li class="slide" ><a href="" target="_blank"><img src=""></a></li>
              <li class="swiper-slide">
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank">
                      <img src="[field:litpic/]" alt="[field:title/]">
                  </a>
                  <h3 class="slide-title">
                      <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank">[field:title/]</a>
                  </h3>
              </li>