<?php
$z[0]=Array("typedir","",26,43);
$z[0][4]=array();
$z[1]=Array("pubdate","",44,90);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y/md',@me)";
$z[2]=Array("id","",91,103);
$z[2][4]=array();
$z[3]=Array("title","",132,147);
$z[3][4]=array();
$z[4]=Array("litpic","",220,236);
$z[4][4]=array();
$z[5]=Array("title","",243,258);
$z[5][4]=array();
$z[6]=Array("title","",327,342);
$z[6][4]=array();

?>