<li class="item">
                        <div class="clearfix">
                            <span class="fl iconfont icon-top10 list list-1"><small>[field:global name=autoindex runphp="yes"] @me; [/field:global]</small></span>
                            <a class="thumbnail fl" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">
                                <img class="img img-cover br" src="[field:litpic/]" alt="[field:title/]" title="[field:title/]">
                            </a>
                            <div class="fr-wrap">
                                <div class="title-wrap">
                                    <h2 class="title ellipsis"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]">[field:title/]</a> </h2>
                                    <p class="intro br clearfix ellipsis"> [field:click/]次下载 </p>
                                </div>
                            </div>
                        </div>
                    </li>