<li class="clearfix">
                <div> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img class="img-cover br" src="[field:litpic/]" alt="[field:title/]" title="[field:title/]"></a> </div>
                <h2 class="ellipsis"><a href="/cyzd/135.html" title="[field:title/]">[field:title/]</a></h2>
                <p> [field:description /] </p>
            </li>