<li>
                  <div  class="pic80"> <a rel="nofollow" href="[field:typedir /]/[field:pubdate function="MyDate('Y/md',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank"> <img src="[field:litpic/]" alt="[field:title/]"/> </a> </div>
                  <a class="title" href="[field:typedir /]/[field:pubdate function="MyDate('Y/md',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank">
                      <h2>[field:title/]</h2>
                  </a>
              </li>