<div class="gj-lg-4 gj-md-3 gj-sm-4 gj-xs-6">
                            <div class="gtw-ul">
                                <div class="gtw-img"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img src="[field:litpic/]" alt="[field:title/]"></a> <span>[field:typename/]</span> </div>
                                <div class="gtw-body"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">
                                    <h4>[field:title/]</h4>
                                    </a>
                                    <p>[field:description /]...</p>
                                    <div class="gtw-sx"> <span>阅读：[field:click/]</span> | <span>发布时间：[field:pubdate function="MyDate('Y/m/d',@me)"/]</span> </div>
                                </div>
                            </div>
                        </div>