<div class="gj-body gli-tuw1">
                        <div class="gtw-li gclear">
                            <div class="gtw-img gj-left"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Y/m-d',@me)"/]/[field:id /].html"><img src="[field:litpic/]" alt=""></a> </div>
                            <div class="gtw-body"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Y/m-d',@me)"/]/[field:id /].html">
                                <h4>[field:title /]</h4>
                                </a> <span><i class="fa fa-clock-o">[field:pubdate function="MyDate('Y/m/d',@me)"/]</i></span> <span><i class="fa fa-eye"> [field:click /]</i></span> </div>
                        </div>
                    </div>