<div class="hot_news_img">
          <div class="hot_pic">
            <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">
              <img src="[field:litpic/]" alt="[field:title/]" /></a>
          </div>
          <h3 class="hot_h4">
            <a class="red" href="/yidong/161.html">[field:title/]</a></h3>
          <p class="hot_text_ms">[field:description /]...</p>
          <div class="hot_text_more">
            <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" class="button3">阅读详细</a></div>
        </div>