<?php
$z[0]=Array("global"," @me=@me+1; ",47,118);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("typedir","",134,151);
$z[1][4]=array();
$z[2]=Array("pubdate","",152,197);
$z[2][4]=array();
$z[2][4]['function']="MyDate('Ymd',@me)";
$z[3]=Array("id","",198,210);
$z[3][4]=array();
$z[4]=Array("title","",224,238);
$z[4][4]=array();
$z[5]=Array("title","",240,254);
$z[5][4]=array();

?>