<div class="cmslist">
              <div class="xyti">
                  <h3> <a href="{dede:field name='typedir'/}/" class="mcolor">dede:field name='typename'/}</a></h3>
              </div>
              <ul>
                  {dede:arclist titlelen='80' row='1'}
                  <li class="first"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" class="pic"> <img class="img-cover br" src="[field:litpic/]" alt="[field:title/]" title="[field:title/]"> </a> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" class="text">[field:title/]</a>
                      <div class="des"> [field:description/]</div>
                  </li>
                  {/dede:arclist}


                  <li> <i class="fa fa-caret-right"></i> <a href="/cyzx/2019-11-19/549.html" title="测试一个没有标题图片也没有内容图片的文章">测试一个没有标题图片也没有内容图片的文章</a> </li>

                  <li> <i class="fa fa-caret-right"></i> <a href="/cyzx/535.html" title="准备在杭州创业？这15家在杭投资机构不能错过">准备在杭州创业？这15家在杭投资机构不能错过</a> </li>

                  <li> <i class="fa fa-caret-right"></i> <a href="/cyzx/532.html" title="疯狂扩张、收缩战线，校园O2O冰火两重天">疯狂扩张、收缩战线，校园O2O冰火两重天</a> </li>

                  <li> <i class="fa fa-caret-right"></i> <a href="/cyzx/534.html" title="一个草根微商暴富梦破：几个月8万亏一半 重回工厂打工">一个草根微商暴富梦破：几个月8万亏一半 重回工厂打工</a> </li>

                  <li> <i class="fa fa-caret-right"></i> <a href="/cyzx/533.html" title="盘点“中国特色”：67个创业项目抢食3大二手回收产业">盘点“中国特色”：67个创业项目抢食3大二手回收产业</a> </li>
              </ul>
          </div>