<?php
$z[0]=Array("field","",80,109);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",141,169);
$z[1][4]=array();
$z[1][4]['name']="typedir";
$z[2]=Array("arclist","\r\n                    <li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a  href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" title=\"[field:title/]\">[field:title/]</a></li>\r\n                    ",261,557);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['row']="5";

?>