<?php
$z[0]=Array("typedir","",30,47);
$z[0][4]=array();
$z[1]=Array("pubdate","",48,94);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y/md',@me)";
$z[2]=Array("id","",95,107);
$z[2][4]=array();
$z[3]=Array("title","",136,151);
$z[3][4]=array();
$z[4]=Array("litpic","",224,240);
$z[4][4]=array();
$z[5]=Array("title","",247,262);
$z[5][4]=array();
$z[6]=Array("title","",331,346);
$z[6][4]=array();

?>