<?php
$z[0]=Array("click","",23,38);
$z[0][4]=array();
$z[1]=Array("global"," @me; ",48,111);
$z[1][4]=array();
$z[1][4]['name']="autoindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("typedir","",124,141);
$z[2][4]=array();
$z[3]=Array("pubdate","",142,187);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Ymd',@me)";
$z[4]=Array("id","",188,200);
$z[4][4]=array();
$z[5]=Array("title","",214,228);
$z[5][4]=array();
$z[6]=Array("title","",230,244);
$z[6][4]=array();

?>