<article class="item fl">
                  <div class="clearfix"> <a class="thumbnail fl" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]"> <img class="img img-cover br" src="[field:litpic /]" alt="[field:title /]" title="[field:title /]"> </a>
                      <div class="fr-wrap">
                          <div class="title-wrap">
                              <h2 class="title ellipsis"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">[field:title /]</a> </h2>
                              <a class="category transition br" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"> [field:typename /]</a>
                              <div class="div"><a rel="nofollow" class="download brightness transition br" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html">下载</a></div>
                          </div>
                      </div>
                  </div>
                  <p class="intro br clearfix multi-ellipsis">[field:description /]... </p>
              </article>