<?php
$z[0]=Array("field","",93,121);
$z[0][4]=array();
$z[0][4]['name']="typedir";
$z[1]=Array("field","",139,168);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                    <li> <i class=\"fa fa-caret-right\"></i> <a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" title=\"[field:title/]\">[field:title/]</a> </li>\r\n                    ",245,522);
$z[2][4]=array();
$z[2][4]['titlelen']="80";
$z[2][4]['limit']="1,5";

?>