<div class="col-md-4 col-xs-12  pc_margintop">
     <section>
      <div class="thleftcon" style="height:363px;">
       <div class="thleftbt thwenzhang">
        <span>{dede:field name='typename'/}</span>
        <div class="listMore">
         <a href="{dede:field name='typedir'/}/">More +</a>
        </div>
       </div>
       <ul class="th-5">
        {dede:arclist titlelen='80' row='8'}
        <li><span class="date">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span><i>[field:global name=autoindex runphp="yes"] @me; [/field:global]</i><a href="/zixun/153.html" title="[field:title/]" target="_blank">[field:title/]</a></li>
        {/dede:arclist}
       </ul>
      </div>
     </section>
    </div>