<div class="col-md-12 col-xs-12  th_padding">
            <div class="thliorder1">
             <div class="thnews-img">
              <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]"><img class="th-img thnews-img-height" src="[field:litpic /]" /></a>
              <span>[field:typename /]</span>
             </div>
             <div class="thnews-con">
              <div class="news-con-tit">
               <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title /]">[field:title /]</a>
              </div>
              <div class="newsummary">
               <p>[field:description /]...</p>
              </div>
              <div class="thinfo">
               时间：[field:pubdate function="MyDate('Y-m-d',@me)"/]&nbsp;&nbsp;|&nbsp;&nbsp;阅读：[field:click /]
              </div>
             </div>
            </div>
           </div>