<li class="list clearfix"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]"> <span class="img-wrap br"> <img src="[field:litpic/]" alt="[field:title/]" class="img-cover br random-img"></span>
                <div class="new-text">
                    <p class="title">[field:title/]</p>
                    <div class="info"> <span class="time"> <i class="iconfont icon-time"></i> <span class="font-oswald">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></span> <span class="comment"> <i class="iconfont icon-comment"></i> <span class="font-oswald">[field:click/]</span></span> </div>
                </div>
                </a> </li>