<li> <a href="" title="[field:title/]" target="_blank"><img src="[field:litpic/]"></a> </li>
                            <div class="swiper-slide">
                                <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img src="[field:litpic/]" alt="[field:title/]">
                                    <p>[field:title/]</p></a>
                            </div>