<?php
$z[0]=Array("field","",59,88);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\n              <li>\n                  <i class=\"ztpic\">\n                      <a href=\"[field:typedir /]/[field:pubdate function=\"MyDate('Ymd',@me)\"/]/[field:id /].html\" target=\"_blank\">\n                        <img src=\"[field:litpic/]\">\n                      </a>\n                  </i>\n                  <b>[field:title/]</b>\n                  <a href=\"\" target=\"_blank\" class=\"readmore\">\n                      <span>[field:pubdate function=\"MyDate('Y年m月d日 ',@me)\"/]</span>\n                  </a>\n              </li>\n              ",123,714);
$z[1][4]=array();
$z[1][4]['titlelen']="80";
$z[1][4]['row']="6";

?>