<li>
                <span class="blogpic imgscale"><i><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"></a></i><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title=""><img src="[field:litpic/]" alt=""></a></span>
                <p class="blogtext"><h3 class="blogtitle"><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank">[field:title/]</a></h3></p>
                <p class="bloginfo"><span>[field:pubdate function="MyDate('Y年m月d日 ',@me)"/]</span></p>
            </li>

            <li class="item">
                <div class="item-img">
                    <a class="item-img-inner" href="/a/fenxiang/94.html" title="抖音培训网：拍的抖音没人看3招帮你解决" target="_blank"> <img class="j-lazy" src="static/picture/lazy.png" data-original="/uploads/200319/1-2003191F313a1.jpg" width="480" height="300" alt="抖音培训网：拍的抖音没人看3招帮你解决"> </a> <a class="item-category" href="/a/fenxiang/" target="_blank">分享</a> </div>
                <div class="item-content">
                    <h2 class="item-title"> <a href="/a/fenxiang/94.html" title="抖音培训网：拍的抖音没人看3招帮你解决" target="_blank"> 抖音培训网：拍的抖音没人看3招帮你解决 </a> </h2>
                    <div class="item-excerpt">
                        <p>&nbsp;  爆火带动了多少网红一夜爆火，给很多普通人带来了新的表达方式，多少产品莫名被抖音带火，让很多自媒体和企业...</p>
                    </div>
                    <div class="item-meta"> <span class="item-meta-li date"></span> <span class="item-meta-li views" title="抖音培训网：拍的抖音没人看3招帮你解决"><i class="fa fa-eye"></i> 7</span> </div>
                </div>
            </li>