<li><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" target="_blank">[field:title/]</a></li>

            <li class="list clearfix"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="史玉柱一刀砍掉巨人中层，企业变革为啥总拿中层开刀？"> <span class="img-wrap br"> <img src="{dede:global.cfg_templets_skin/}/static/img/69870d0d1420c4c7f536e1b3922878d3.jpg" alt="史玉柱一刀砍掉巨人中层，企业变革为啥总拿中层开刀？" class="img-cover br random-img"></span>
                <div class="new-text">
                    <p class="title">史玉柱一刀砍掉巨人中层，企业变革为啥总拿中层开刀？</p>
                    <div class="info"> <span class="time"> <i class="iconfont icon-time"></i> <span class="font-oswald">2016-01-01</span></span> <span class="comment"> <i class="iconfont icon-comment"></i> <span class="font-oswald">854</span></span> </div>
                </div>
            </a>
            </li>