<li class="item">
          <div class="item-img">
              <a class="item-img-inner" href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank">
              <img class="j-lazy" src="[field:litpic/]" data-original="[field:litpic/]" width="480" height="300" alt="[field:title/]">
              </a>
              <a class="item-category" href="[field:typedir/]" target="_blank">[field:typename/]</a> </div>
          <div class="item-content">
              <h2 class="item-title">
                  <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]" target="_blank"> [field:title/] </a>
              </h2>
              <div class="item-excerpt">
                  <p>&nbsp;  [field:description /]...</p>
              </div>
              <div class="item-meta">
                  <span class="item-meta-li date"></span>
                  <span class="item-meta-li views" title="[field:title/]">
                            <i class="fa fa-eye"></i> [field:click/]
                        </span>
              </div>
          </div>
      </li>

            <div class="block">
                <h2>
                    <span class="category">
                        <a href="[field:typedir/]" rel="category tag" >[field:typename/]</a><i class="fa fa-caret-right"></i>
                    </span>
                    <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"  target="_ablank" >[field:litpic/]</a></h2>
                <div class="clear"></div>

                <div class='viewimg'> <a href='/News/1.html' title='如果没有略缩图，就不会显示前面的图片！' target='_ablank' class='ipic'> <img src='/uploads/170530/1-1F5301S915S8.gif' alt='如果没有略缩图，就不会显示前面的图片！' class='thumbnail' /><span class='shine' style='background-position: 160px 50%;'> </span></a> </div>

                <div class="preview"> 如果没有略缩图，就不会显示前面的图片！如果没有略缩图，就不会显示前面的图片！如果没有略缩图，就不会显示前面的图片！如果没有略缩图，就不会显示前面的图片！如果没有略缩图，就…… </div>
                <div class="preem"> <span><i class="fa fa-clock-o"></i> 05-30 </span><span><i class="fa fa-comment-o"></i> <a href="/News/1.html" class="ds-thread-count" data-thread-key="156">暂无评论</a> </span><span><i class="fa fa-eye"></i> 143 </span><span> </span><span class="more"><a href="/News/1.html" title="如果没有略缩图，就不会显示前面的图片！">阅读详情</a></span> </div>
            </div>