<li><a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html"><img src="[field:litpic/]"><span>[field:title/]</span></a></li>
                  <li>
                      <i></i>
                      <a href="[field:typedir /]/[field:pubdate function="MyDate('Ymd',@me)"/]/[field:id /].html" title="[field:title/]</a>
                      <p> [field:description/]...</p>
                  </li>