<div class="content">
                <div class="content-header">
                    <a href="[field:typedir /]/[field:pubdate function="MyDate('Y/md',@me)"/]/[field:id /].html" title="[field:title /]" target="_blank"><h2>[field:title /]</h2></a>
                    <div class="content-info">
                        <span class="mr10 postclock">[field:pubdate function="MyDate('Y-m-d ',@me)"/]</span>
                        <span class="mr10 postuser">[field:typename/]<a></a></span>
                        <span class="mr10 posteye"><i class=" icon-eye" ></i>[field:click/]</span>
                    </div>
                </div>

                <div class="content-img"> <a href="[field:typedir /]/[field:pubdate function="MyDate('Y/md',@me)"/]/[field:id /].html" title="[field:title /]" target="_blank"> <img class="lazy thumbnail" src="[field:litpic /]" data-original="[field:litpic /]" alt="[field:title /]" /> </a> </div>
                <div class="content-note">
                    <p>[field:description /]...</p>
                    <span class="category-color"><a href="[field:typedir /]">[field:typename /]</a></span>
                </div>
            </div>