<?php
$z[0]=Array("typedir","",31,48);
$z[0][4]=array();
$z[1]=Array("pubdate","",49,94);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Ymd',@me)";
$z[2]=Array("id","",95,107);
$z[2][4]=array();
$z[3]=Array("litpic","",177,192);
$z[3][4]=array();
$z[4]=Array("litpic","",209,224);
$z[4][4]=array();
$z[5]=Array("title","",231,245);
$z[5][4]=array();
$z[6]=Array("title","",293,307);
$z[6][4]=array();

?>