<?php
$z[0]=Array("global","",349,375);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",422,448);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",573,597);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",620,647);
$z[3][4]=array();
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",804,829);
$z[4][4]=array();
$z[4][4]['name']="cfg_lianxi";

?>