<?php
$z[0]=Array("flink","\r\n    [field:link /]\r\n    ",111,209);
$z[0][4]=array();
$z[0][4]['row']="24";
$z[0][4]['type']="text";
$z[0][4]['titlelen']="24";
$z[0][4]['typeid']="0";
$z[1]=Array("global","",510,536);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",583,609);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",734,758);
$z[3][4]=array();
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",781,808);
$z[4][4]=array();
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",965,990);
$z[5][4]=array();
$z[5][4]['name']="cfg_lianxi";

?>