<?php
$z[0]=Array("global","",150,176);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",201,227);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("global","",257,283);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",292,318);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("field","(@me=='0') ? @me='active' : @me=''; ",599,685);
$z[4][4]=array();
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[5]=Array("channel","\n                    <li><a href=\"[field:typelink /]\">[field:typename/]</a></li>\n                    ",723,939);
$z[5][4]=array();
$z[5][4]['type']="top";
$z[5][4]['currentstyle']="<li><a href=\"~typelink~\" class=\"active\">~typename~</a></li>";

?>