<?php
$z[0]=Array("global","",155,182);
$z[0][4]=array();
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",205,231);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",240,266);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","(@me=='0') ? @me='selected' : @me=''; ",364,452);
$z[3][4]=array();
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channel","\r\n                <li><a href=\"[field:typelink /]\">[field:typename/]</a></li>\r\n                ",487,696);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li><a href=\"~typelink~\" id=\"selected\">~typename~</a></li>";

?>